function QuatGUItest
    clc; close all; clear all;
    
    % Instantiate Quaternion
    Q = MyQuaternion(1.0, [0.0 0.0 0.0]);

    % Create figure window
    hFig = figure;
    set(hFig,...
        'Units', 'Pixels',...
        'Position', [450 200 800 500] ...
        );
    
    hAxes = axes;
    set(hAxes, ...
      'Parent', hFig,...
      'Units', 'Pixels',...
      'Position', [30 30 440 440],...
      'XLim', [-1 1],...
      'XTick', -1:.5:1,...
      'XGrid', 'on',...
      'YLim', [-1 1],...
      'YTick', -1:.5:1,...
      'YGrid', 'on',...
      'ZLim', [-1 1],...
      'ZTick', -1:.5:1,...
      'ZGrid', 'on',...
      'Color', 'w',...
      'ButtonDownFcn', @startRotate_Callback ...
    );

    view(-50, 20);

    cntrlPanel = uipanel;
    set(cntrlPanel,...
        'Parent', hFig,...
        'Units', 'Pixels',...
        'Position', [500 30 280 440] ...
    );

    axis vis3d;
    draw_axes;
    
    hold on;
    quiver3(0, 0, 0, sind(45)*cosd(45), sind(45)*sind(45), cosd(45));
    
    % ********************************** %
    % **********  Functions  *********** %
    % ********************************** %
    
    function draw_axes
        h = ishold;
        hold on;
        line([-10 10], [0 0], [0 0], 'Color', 'k');
        line([0 0], [-10 10], [0 0], 'Color', 'k');
        line([0 0], [0 0], [-10 10], 'Color', 'k');
        if ~h
            hold off;
        end
    end

    function startRotate_Callback(source, ~)
        for az = -50 : .2 : 30
            view(az, 20)
            drawnow
        end 
    end

end

